Repository spoticket/spoticket, pull requests merged in 2025-01, with the labels that each got.

#6 [Feat] 엔티티 클래스 작성
  .gitignore
  com.spoticket.games/build.gradle
  com.spoticket.games/src/main/java/com/spoticket/game/GameApplication.java
  com.spoticket.games/src/main/java/com/spoticket/game/TestController.java
  com.spoticket.games/src/main/java/com/spoticket/game/domain/model/Game.java
  com.spoticket.games/src/main/java/com/spoticket/game/domain/model/Sport.java
  com.spoticket.games/src/main/java/com/spoticket/game/domain/repository/GameRepository.java
  com.spoticket.games/src/main/java/com/spoticket/game/dto/response/GameResponse.java
  com.spoticket.games/src/main/java/com/spoticket/game/global/entity/BaseEntity.java
  com.spoticket.games/src/main/java/com/spoticket/game/global/exception/CustomException.java
  com.spoticket.games/src/main/java/com/spoticket/game/global/exception/GlobalExceptionHandler.java
  com.spoticket.games/src/main/java/com/spoticket/game/global/util/ResponseUtils.java
  com.spoticket.games/src/main/java/com/spoticket/game/test/TestController.java
  com.spoticket.games/src/main/resources/application.yml
  com.spoticket.games/src/test/java/com/spoticket/game/GameApplicationTests.java
  com.spoticket.gateway/src/main/resources/application.yml
  com.spoticket.payment/src/main/resources/application.yml
  com.spoticket.server/src/main/resources/application.yml
  com.spoticket.team-stadium/src/main/resources/application.yml
  com.spoticket.ticket/src/main/resources/application.yml
  com.spoticket.user/src/main/resources/application.yml
Labels: feature

#7 [Feat] 경기 CRUD 구현
  com.spoticket.games/build.gradle
  com.spoticket.games/src/main/java/com/spoticket/game/application/service/GameCommandService.java
  com.spoticket.games/src/main/java/com/spoticket/game/application/service/GameQueryService.java
  com.spoticket.games/src/main/java/com/spoticket/game/domain/model/Game.java
  com.spoticket.games/src/main/java/com/spoticket/game/domain/repository/GameRepository.java
  com.spoticket.games/src/main/java/com/spoticket/game/dto/request/CreateGameRequest.java
  com.spoticket.games/src/main/java/com/spoticket/game/dto/request/UpdateGameRequest.java
  com.spoticket.games/src/main/java/com/spoticket/game/dto/response/GenericPagedModel.java
  com.spoticket.games/src/main/java/com/spoticket/game/global/entity/BaseEntity.java
  com.spoticket.games/src/main/java/com/spoticket/game/global/exception/CustomException.java
  com.spoticket.games/src/main/java/com/spoticket/game/global/util/ErrorUtils.java
  com.spoticket.games/src/main/java/com/spoticket/game/global/util/ResponseUtils.java
  com.spoticket.games/src/main/java/com/spoticket/game/presentation/controller/GameController.java
  com.spoticket.games/src/main/java/com/spoticket/game/test/TestController.java
  com.spoticket.games/src/test/java/com/spoticket/game/application/service/GameQueryServiceTest.java
Labels: feature

#39 [FEAT] #15: User Entity 작성 및 공통, 유틸 작성
  com.spoticket.user/build.gradle
  com.spoticket.user/src/main/java/com/spoticket/user/domain/model/User.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/model/UserRole.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/entity/BaseEntity.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/exception/CustomException.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/exception/GlobalExceptionHandler.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/ResponseUtils.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/SecurityConfig.java
Labels: feature

#46 [Feat] Ticket 생성 기능 구현
  com.spoticket.ticket/.gitignore
  com.spoticket.ticket/build.gradle
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/TicketApplication.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/request/CreateTicketRequest.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/request/UpdateTicketStatusRequest.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/TicketInfoResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/TicketResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/TicketService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/domain/entity/Ticket.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/domain/entity/TicketStatus.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/domain/repository/TicketRepository.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/entity/BaseEntity.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/exception/ApiResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/exception/BusinessException.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/exception/ErrorCode.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/exception/GlobalExceptionHandler.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/presentation/TicketController.java
Labels: feature

#50 [Feat] Ticket 단일 조회 기능 구현
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/TicketInfoResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/TicketService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/exception/ErrorCode.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/presentation/TicketController.java
Labels: feature

#54 [FEAT] ApiResponse 변수 이름 수정
  com.spoticket.payment/build.gradle
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/common/BaseException.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/common/ErrorCode.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/exception/OrderErrorCode.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/exception/OrderException.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/model/Order.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/model/OrderItem.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/model/OrderStatus.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/repository/OrderItemRepository.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/repository/OrderRepository.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/exception/PaymentErrorCode.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/exception/PaymentException.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/PaymentHistories.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/PaymentMethod.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/PaymentStatus.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/Payments.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/presentation/common/ApiErrorResponse.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/presentation/common/ApiSuccessResponse.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/presentation/common/GlobalExceptionHandler.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/presentation/order/controller/OrderController.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/presentation/payment/controller/PaymentController.java
Labels: feature

#58 [Feat] 경기 알림 구현
  com.spoticket.games/build.gradle
  com.spoticket.games/src/main/java/com/spoticket/game/GameApplication.java
  com.spoticket.games/src/main/java/com/spoticket/game/application/service/GameNotificationService.java
  com.spoticket.games/src/main/java/com/spoticket/game/domain/repository/GameRepository.java
  com.spoticket.games/src/main/java/com/spoticket/game/dto/response/TicketResponse.java
  com.spoticket.games/src/main/java/com/spoticket/game/dto/response/TicketStatus.java
  com.spoticket.games/src/main/java/com/spoticket/game/global/entity/BaseEntity.java
  com.spoticket.games/src/main/java/com/spoticket/game/infrastructure/slack/SlackClient.java
  com.spoticket.games/src/main/java/com/spoticket/game/presentation/controller/GameController.java
Labels: feature

#64 [FEAT] 사용자 권한 변경
  com.spoticket.gateway/src/main/resources/authorization-rule.yml
  com.spoticket.user/build.gradle
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserService.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/ResponseStatus.java
  com.spoticket.user/src/main/java/com/spoticket/user/presentation/controller/UserController.java
Labels: feature

#68 [Feat] Ticket 목록 조회 기능 구현
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/request/TicketSearchCriteria.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/TicketService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/domain/repository/TicketRepository.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/domain/repository/TicketRepositoryCustom.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/domain/repository/TicketRepositoryImpl.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/QueryDslConfig.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/exception/GlobalExceptionHandler.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/util/ApiResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/util/PagedApiResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/presentation/TicketController.java
Labels: feature

#70 [FEAT] Coupon CRUD 구현
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/CouponService.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/repository/CouponRepository.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/exception/ErrorStatus.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/ResponseStatus.java
  com.spoticket.user/src/main/java/com/spoticket/user/presentation/controller/CouponController.java
  com.spoticket.user/src/main/java/com/spoticket/user/presentation/controller/UserController.java
Labels: feature

#71 [FEAT] 회원정보 수정
  com.spoticket.gateway/src/main/resources/authorization-rule.yml
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserService.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/ResponseStatus.java
  com.spoticket.user/src/main/java/com/spoticket/user/presentation/controller/UserController.java
Labels: feature

#72 [FEAT] 회원탈퇴
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserService.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/ResponseStatus.java
  com.spoticket.user/src/main/java/com/spoticket/user/presentation/controller/UserController.java
Labels: feature

#75 [FIX] #74: authorization-rule wildcard fix
  com.spoticket.gateway/src/main/java/com/spoticket/gateway/global/util/AuthorizationFilter.java
Labels: bug, fix

#76 [Fix] team, stadium 서비스 미구현 부분 수정
  com.spoticket.team-stadium/build.gradle
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/TeamStadiumApplication.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/application/dto/response/PagedGameResponse.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/application/service/SeatService.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/application/service/StadiumService.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/application/service/TeamService.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/domain/model/UserRoleEnum.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/exception/ErrorCode.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/exception/FeignErrorDecoder.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/global/common/BaseEntity.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/global/util/RequestUtils.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/infrastructure/config/FeignClientConfig.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/infrastructure/feign/GameServiceClient.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/presentation/SeatController.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/presentation/StadiumController.java
  com.spoticket.team-stadium/src/main/java/com/spoticket/teamstadium/presentation/TeamController.java
  com.spoticket.team-stadium/src/test/java/com/spoticket/teamstadium/service/TeamServiceTest.java
Labels: fix

#78 [FEAT] UserCoupon issue,use,get
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserCouponService.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/model/entity/UserCoupon.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/repository/UserCouponRepository.java
  com.spoticket.user/src/main/java/com/spoticket/user/dto/response/UserCouponResponseDto.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/exception/ErrorStatus.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/ResponseStatus.java
  com.spoticket.user/src/main/java/com/spoticket/user/presentation/controller/UserCouponController.java
Labels: feature

#77 [Fix] Ticket FeignClient 적용하여 단일 조회 수정
  com.spoticket.games/build.gradle
  com.spoticket.gateway/src/main/java/com/spoticket/gateway/global/util/AuthorizationFilter.java
  com.spoticket.ticket/build.gradle
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/TicketApplication.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/request/CreateTicketRequest.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/GameResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/StadiumInfoResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/StadiumReadResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/TicketInfoResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/TicketResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/UserResponseDto.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/TicketService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/domain/entity/Ticket.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/FeignConfig.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/exception/CustomErrorDecoder.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/util/UserContextUtil.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/infrastructure/GameServiceClient.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/infrastructure/StadiumServiceClient.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/infrastructure/UserServiceClient.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/presentation/TicketController.java
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/CouponService.java
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserService.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/repository/CouponRepository.java
Labels: feature, fix

#80 [FIX] user gateway
  com.spoticket.gateway/src/main/java/com/spoticket/gateway/global/util/AuthorizationFilter.java
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserService.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/ResponseStatus.java
Labels: bug, fix

#85 [FIX] User 서버 엔티티의 스키마 지정
  com.spoticket.user/src/main/java/com/spoticket/user/domain/model/entity/Coupon.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/model/entity/User.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/model/entity/UserCoupon.java
Labels: fix

#86 [FIX] 쿠폰 발급 시 재고 감소처리
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserCouponService.java
Labels: bug, fix

#88 [FIX] JpaAuditing Fix
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/AuditingConfig.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/AuditorAwareImpl.java
Labels: bug, fix

#89 [FEAT]결제 관련 서비스 로직 추가 및 수정
  com.spoticket.payment/build.gradle
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/payment/dto/PaymentCreateReq.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/payment/dto/PaymentRes.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/payment/service/PaymentService.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/exception/PaymentErrorCode.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/CardCompany.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/PaymentHistories.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/PaymentMethod.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/PaymentStatus.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/Payments.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/port/TossPaymentPort.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/repository/PaymentHistoryRepository.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/repository/PaymentRepository.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/service/PaymentDomainService.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/toss/TossClient.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/toss/adaptor/TossPaymentAdapter.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/toss/dto/TossCancelPaymentReq.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/toss/dto/TossPaymentFailureRequest.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/toss/dto/TossPaymentReq.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/toss/dto/TossPaymentRes.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/presentation/payment/controller/PaymentController.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/presentation/payment/controller/PaymentViewController.java
  com.spoticket.payment/src/main/resources/static/css/style.css
  com.spoticket.payment/src/main/resources/templates/fail.html
  com.spoticket.payment/src/main/resources/templates/payment.html
  com.spoticket.payment/src/main/resources/templates/success.html
Labels: feature

#94 [FIX] UserCouponDto에 Payment에서 필요한 정보 추가
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserCouponService.java
  com.spoticket.user/src/main/java/com/spoticket/user/dto/response/UserCouponResponseDto.java
Labels: fix

#97 [FEATURE] 티켓 생성 동시성 문제 해결
  com.spoticket.ticket/build.gradle
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/TicketService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/CacheConfig.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redisson/AopForTransaction.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redisson/DistributedLock.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redisson/DistributedLockAop.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redisson/RedissonConfig.java
Labels: feature

#108 [FEAT] Kafka 토픽 구독을 이용한 쿠폰 사용처리
  com.spoticket.user/build.gradle
  com.spoticket.user/src/main/java/com/spoticket/user/domain/model/entity/UserCoupon.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/service/KafkaConsumer.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/service/KafkaProducerService.java
  com.spoticket.user/src/main/java/com/spoticket/user/domain/service/KafkaProducerServiceImpl.java
Labels: feature

#106 [FEAT] Redis를 이용한 선착순 쿠폰 발급
  com.spoticket.user/build.gradle
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/CouponService.java
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserCouponService.java
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserService.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/config/AuditingConfig.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/config/RedisConfig.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/config/SecurityConfig.java
Labels: feature

#109 [FEATURE] 구역별 좌석들 캐싱
  com.spoticket.gateway/src/main/java/com/spoticket/gateway/GatewayApplication.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/TicketApplication.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/TicketResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/TicketService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/domain/repository/TicketRepository.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/CacheConfig.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/RedisConfig.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redisson/RedissonConfig.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/presentation/TicketController.java
Labels: feature

#113 [FIX] 티켓 단건 조회 수정
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/request/CreateTicketRequest.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/SeatReadResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/TicketInfoResponse.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/TicketService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/infrastructure/StadiumServiceClient.java
Labels: fix

#116 [FIX] 쿠폰발급에 대한 동시성 문제 해결
  com.spoticket.user/build.gradle
  com.spoticket.user/src/main/java/com/spoticket/user/application/service/UserCouponService.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/config/RedissonConfig.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/lock/AopForTransaction.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/lock/CustomSpringELParser.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/lock/DistributedLock.java
  com.spoticket.user/src/main/java/com/spoticket/user/global/util/lock/DistributedLockAop.java
Labels: bug, fix

#117 [Fix] 게임 알림 서비스에서 발생하는 에러 해결
  .gitignore
  com.spoticket.games/src/main/java/com/spoticket/game/application/service/GameNotificationService.java
  com.spoticket.gateway/src/main/resources/application.yml
  com.spoticket.server/src/main/resources/application.yml
  com.spoticket.ticket/src/main/resources/application.yml
  com.spoticket.user/src/main/resources/application.yml
Labels: fix

#119 [FEATURE] 오더 서비스 리팩토링 및 카프카 연결
  .gitignore
  com.spoticket.gateway/src/main/resources/authorization-rule.yml
  com.spoticket.payment/.gitignore
  com.spoticket.payment/src/main/java/com/spoticket/payment/PaymentApplication.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/order/dto/CouponUsedEvent.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/order/dto/CreateOrderReq.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/order/dto/OrderRes.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/order/dto/PaymentCompletedEvent.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/order/dto/PaymentRequestEvent.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/order/listener/PaymentCompletedEventListener.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/order/service/OrderKafkaService.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/order/service/OrderService.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/payment/dto/PaymentEventRes.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/payment/listener/PaymentEventListener.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/payment/service/PaymentKafkaService.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/application/payment/service/PaymentService.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/model/Order.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/model/OrderItem.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/order/service/OrderDomainService.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/model/PaymentConsumer.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/domain/payment/repository/PaymentConsumerRepository.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/messaging/config/KafkaConsumerConfig.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/messaging/config/KafkaProducerConfig.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/order/feign/client/CouponServiceClient.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/order/feign/client/TicketServiceClient.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/order/feign/dto/CouponResponse.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/order/feign/dto/TicketInfoResponse.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/order/feign/dto/UserCouponResponseDto.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/order/feign/ticket/TicketStatus.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/infrastrucutre/toss/dto/TossPaymentRes.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/presentation/order/controller/OrderController.java
  com.spoticket.payment/src/main/java/com/spoticket/payment/presentation/payment/controller/PaymentViewController.java
  com.spoticket.payment/src/main/resources/templates/payment.html
  com.spoticket.payment/src/main/resources/templates/success.html
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/response/TicketInfoResponse.java
Labels: feature

#121 [FEATURE] Redis를 활용한 대기열 구축
  com.spoticket.ticket/build.gradle
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/TicketApplication.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/dtos/request/UserWaitRequest.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/QueueService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/TicketService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redis/redisson/AopForTransaction.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redis/redisson/CacheConfig.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redis/redisson/DistributedLock.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redis/redisson/DistributedLockAop.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/config/redis/redisson/RedisConfig.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/global/util/QueueNotifier.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/presentation/QueueController.java
  com.spoticket.ticket/src/main/resources/static/queue.html
  com.spoticket.ticket/src/test/java/com/spoticket/ticket/queue/QueueServiceTest.java
Labels: feature

#123 [Feat] Grafana 연동
  com.spoticket.ticket/build.gradle
  com.spoticket.ticket/prometheus.txt
  com.spoticket.ticket/prometheus.yml
Labels: feature

#129 [FIX] 티켓 생성 시 상태 확인 오류
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/application/service/TicketService.java
  com.spoticket.ticket/src/main/java/com/spoticket/ticket/domain/repository/TicketRepository.java
Labels: fix
